Implementacion del Cliente Api
DavidCaidas/rss-aggregator pull request #14
Opened 2022-12-04 10:45 UTC by DavidCaidas

## Description de la tarea

En esta PR creamos nuestro cliente api, que recogerá datos rss de paginas web que introduzcamos.

## ¿Cómo se ha implementado?

importamos retrofit y la librer,ia simple XML (deprecated), construimos los modelos Api que van a ser la estructura de las rss.

Disclaimer: 
1. el ApiModel de Rss se lo copié a Chema porque no sabía sacarlo.
2.  en esta pull request no sé si estará especificamente vinculada al issue que debería, ya que hice todos los cambios en una rama y después supe que hay que sacar la rama directamente del issue, en esta pr estoy comparando la rama de los cambios con la del issue

## Keywords

ApiClient, RetroFit, XML, ApiModel, Data, ApiServices

2022-12-04 20:54 UTC, OscarAntona commented on app/src/main/java/com/example/myapplication/data/remote/api/RssApiModel.kt
> +data class ItemApiModel @JvmOverloads constructor(
Esto esta correcto, pero recuerda que solo estas recogiendo el titulo las noticias con tu modelo, si luego necesitas alguna cosa mas, te va a tocar cambiarlo, te lo digo, solamente para que lo tengas en cuenta

2022-12-04 20:58 UTC, DavidCaidas commented on app/src/main/java/com/example/myapplication/data/remote/api/RssApiModel.kt
> +data class ItemApiModel @JvmOverloads constructor(
va fino, en la issue pone poco faltan datos que me tocará añadir mas adelante

2022-12-04 21:05 UTC, OscarAntona requested changes
Por lo demas, poco mas te puedo comentar, todo parece correcto👍, aun asi no te puedo dar el approve, por lo que te he dicho sobre el manifest y sobre todo por que el ticket dice que hay que comprobar que la informacion se ha recogido correctamente, con que te crees un main activity para comprobarlo seria suficiente, cuando lo tengas listo, pideme otra revision y te doy el approve

2022-12-04 21:46 UTC, OscarAntona commented on app/src/main/java/com/example/myapplication/data/remote/api/RssApiModel.kt
> +data class ItemApiModel @JvmOverloads constructor(
siiii, por eso te digo que no te preocupes, era más que nada para que lo supieras

2022-12-13 08:45 UTC, OscarAntona approved these changes
Ahora si, todo correcto tio👌👌, de todas formas espera a que te eche un ojo chema

2022-12-13 22:30 UTC, merged